name: River Alerts

on:
  push:
    branches:
      - "main"

env:
  CLOUD_RUN_PROJECT_ID: ${{ secrets.CLOUD_RUN_PROJECT_NAME }}
  CLOUD_RUN_REGION: ${{ secrets.CLOUD_RUN_REGION }}
  REPO_NAME: River Alerts

jobs:
  build-and-deploy:
    name: Setup, Build, and Deploy
    runs-on: ubuntu-latest

    steps:

      # 1. Checkout
      - name: Checkout
        uses: actions/checkout@v2

      # 2. Authenticate Service Account
      - name: Authenticate Service Account
        uses: google-github-actions/setup-gcloud@v0.2.1
        with:
          project_id: ${{ secrets.CLOUD_RUN_PROJECT_NAME }}
          service_account_key: ${{ secrets.CLOUD_RUN_SERVICE_ACCOUNT }}
          service_account_email: ${{ secrets.CLOUD_RUN_SERVICE_ACCOUNT_EMAIL }}

      # 3. Enable the necessary APIs and enable docker auth
      - name: Enable the necessary APIs and enable docker auth
        run: |-
          gcloud services enable containerregistry.googleapis.com
          gcloud services enable run.googleapis.com
          gcloud --quiet auth configure-docker

      # 4. Build and tag image
      - name: Build and tag image
        run: |-
          docker build . --tag "gcr.io/$CLOUD_RUN_PROJECT_ID/riveralerts:$GITHUB_SHA"

      # 5. Push image to GCR
      - name: Push image to GCR
        run: |-
          docker push gcr.io/$CLOUD_RUN_PROJECT_ID/riveralerts:$GITHUB_SHA

      # 6. Deploy
      - name: Deploy
        run: |-
          gcloud components install beta --quiet
          gcloud beta run deploy riveralerts --image gcr.io/$CLOUD_RUN_PROJECT_ID/riveralerts:$GITHUB_SHA \
            --project $CLOUD_RUN_PROJECT_ID \
            --platform managed \
            --region $CLOUD_RUN_REGION \
            --allow-unauthenticated \
            --quiet
